apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: flask
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
